name: Example
packages:
  BlueDress:
    url: https://github.com/noppefoxwolf/BlueDress
    branch: master
targets:
  App:
    platform: iOS
    deploymentTarget: "13.0"
    type: application
    sources:
      - path: App
    settings:
      base:
        DEVELOPMENT_TEAM: FBQ6Z8AF3U
        PRODUCT_BUNDLE_IDENTIFIER: dev.noppe.iOSDC20
        SWIFT_OBJC_BRIDGING_HEADER: App/Resources/Bridging-Header.h
    dependencies:
      - package: BlueDress
      - framework: HandTracker.framework
